{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.49b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymysql-{{ version }}.tar.gz
  sha256: d2068ac7c84ad0af75119bf4725b62e0c17ea55b85db8ea74c98a02208327f7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.49b2
    - opentelemetry-instrumentation ==0.49b2
    # - pymysql <2
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
