{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.55b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymysql-{{ version }}.tar.gz
  sha256: f0ce74d4949e01f334e451d18692637155bf593e285557b62a691d407489212c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.55b1
    - opentelemetry-instrumentation ==0.55b1
    # - pymysql <2
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2
    # - pymysql <2


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
