{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.25b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-pymysql-{{ version }}.tar.gz
  sha256: 3a2a0fa8ef004ec623e08d5a9db4d43a2c015e602b2722b1a104f4af42acfc84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b2
    - opentelemetry-instrumentation-dbapi ==0.25b2
    - python >=3.6
    # - pymysql ~=0.10.1
    # - opentelemetry-test ==0.24b0
    # - pymysql ~=0.10.1
    # - opentelemetry-test ==0.25b0
    # - pymysql ~=0.10.1
    # - opentelemetry-test ==0.25b2

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
