{% set name = "opentelemetry-instrumentation-pymysql" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymysql-{{ version }}.tar.gz
  sha256: fd0a0d24297f125ec9bda94654d6babd36d5d82139e1d6ba25bd6ab638ea3e0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-dbapi ==0.42b0
    - opentelemetry-instrumentation ==0.42b0
    # - pymysql <2
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymysql 
    # - pymysql <2
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pymysql 


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymysql
  summary: OpenTelemetry PyMySQL instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
